apiVersion: v1
appVersion: 0.0.13
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: hello-shutterfly
version: 0.0.13
